### ISSUE TITLE
Several Issues in README

### ISSUE THREAD

**Issue by pysan3** [HaiminLuo/Artemis#3]
Hi, first of all, thank you for releasing the code. I am really looking forward to trying it.

I stumbled across some issues following the README so could you provide me solutions to them?

### 1. In [requirements.txt](https://github.com/HaiminLuo/Artemis/blob/29c630b25288fcf490b87352df88d029bc92057c/requirement.txt), `PIL` does not exist.

Should be `pillow` instead.

### 2. [svox_t](https://github.com/HaiminLuo/svox_t) returns 404

Probably it is a private repository? Is there any chance you can make this a public repository?

### 3. Pre-trained model link is wrong

The link [pre-trained models](https://shanghaitecheducn-my.sharepoint.com/:f:/g/personal/luohm_shanghaitech_edu_cn/Et60lJpJdp5DoyQF7uzP6jgB_JEW4LIHixAyXEiVhHT3Vw?e=0UtltU) points to the same URL as [DFA datasets](https://shanghaitecheducn-my.sharepoint.com/:f:/g/personal/luohm_shanghaitech_edu_cn/Et60lJpJdp5DoyQF7uzP6jgB_JEW4LIHixAyXEiVhHT3Vw?e=d09jtz).

I could not find files such as `./model/cat/configs.yml` or `./model/cat/model.pt` in the DFA datasets. Would you mind guiding me to the models?

Thanks in advance,
@pysan3

**Comment by HaiminLuo** [comment]
Hi, thanks for your interest. The mentioned issues have been fixed and I have updated the link to the pre-trained models. The repository svox_t has been made public. Thanks for your reminder.

**Comment by pysan3** [comment]
Thank you for your quick response. I can see them now.

Keep up with your hard work!
